// <auto-generated />
using System;
using Exchange.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exchange.Data.Sqlite.Migrations
{
    [DbContext(typeof(ExchangeDataContext))]
    partial class ExchangeDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Exchange.Domain.DataInterfaces.ExchangeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExchangeUsers");
                });

            modelBuilder.Entity("Exchange.Domain.DataInterfaces.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HolderId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Exchange.Domain.DataInterfaces.Item", b =>
                {
                    b.HasOne("Exchange.Domain.DataInterfaces.ExchangeUser", "Holder")
                        .WithMany("ItemList")
                        .HasForeignKey("HolderId");

                    b.Navigation("Holder");
                });

            modelBuilder.Entity("Exchange.Domain.DataInterfaces.ExchangeUser", b =>
                {
                    b.Navigation("ItemList");
                });
#pragma warning restore 612, 618
        }
    }
}
